---
- name: Add fish to list of available shells
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
  become: true

- name: Make fish the default shell
  shell: chsh -s /usr/local/bin/fish
  become: true

- name: Create fish config directory
  file:
    path: ~/.config/fish
    state: directory

- name: Create fish config file
  file:
    path: ~/.config/fish/config.fish
    state: touch

- name: Add /usr/local/bin to path
  lineinfile:
    path: ~/.config/fish/config.fish
    line: set -g -x PATH /usr/local/bin $PATH

- name: Ensure commands starting with a space are not logged to history
  lineinfile:
    path: ~/.config/fish/config.fish
    line: set HISTCONTROL ignorespace