- name: A playbook to setup new macs for dev
  hosts: localhost
  connection: local
  vars_prompt:
  - name: "sudo_password"
    prompt: "Enter sudo password to allow binary install"
    private: yes
  - name: "git_username"
    prompt: "Enter name for git commits"
    private: no
  - name: "git_email"
    prompt: "Enter email for git commits"
    private: no
  roles:
   - { role: whoami }
   - { role: git-config }
   - { role: brews }
   - { role: casks }
