- name: A playbook to setup new macs for dev
  hosts: localhost
  connection: local
  vars_prompt:
  - name: "git_username"
    prompt: "Enter name for git commits"
    private: no
  - name: "git_email"
    prompt: "Enter email for git commits"
    private: no
  roles:
   - { role: brews }
   - { role: casks }
   - { role: git-config }
   - { role: ssh-key }
   - { role: fish }
