---
- name: Install larger packages via brew cask 
  homebrew_cask:
    name: ["{{ item }}"]
    # The list syntax on name is due to https://github.com/ansible/ansible/issues/29428
    state: present
  with_items:
    - pycharm-ce
    - intellij-idea-ce
    - java
    - docker
    - spectacle
    - iterm2
    - spotify
    - 1password
    - sublime-text
    - slack
    - google-chrome
    - vagrant